###
POST http://localhost:3000/reminders/ HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWIyN2JhN2MxMWE0ZDI3YjMyMzk0N2YiLCJudW1iZXIiOiI5MTk3MTg0OTc2NzZAYy51cyIsImNoYXRJZCI6IjkxOTcxODQ5NzY3NkBjLnVzIiwiaXNWZXJpZmllZCI6ZmFsc2UsIl9fdiI6MCwiZW1haWwiOiJkaGFpcnlhc2hhaDk4QGdtYWlsLmNvbSIsImlhdCI6MTcwNjIwNjUzOX0.2YcJy91STE4UXU4NNtbN052W1ok8rBjDGhvjgLhPz-o

{
  "message": "take a bath",
  "time": "2024-01-26T00:22:00.000Z"
}
###

PUT http://localhost:3000/reminders/65b2ad62fde6bfeb3cbc89b0 HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWIyN2JhN2MxMWE0ZDI3YjMyMzk0N2YiLCJudW1iZXIiOiI5MTk3MTg0OTc2NzZAYy51cyIsImNoYXRJZCI6IjkxOTcxODQ5NzY3NkBjLnVzIiwiaXNWZXJpZmllZCI6ZmFsc2UsIl9fdiI6MCwiZW1haWwiOiJkaGFpcnlhc2hhaDk4QGdtYWlsLmNvbSIsImlhdCI6MTcwNjIwNjUzOX0.2YcJy91STE4UXU4NNtbN052W1ok8rBjDGhvjgLhPz-o

{
  "time": "2024-01-25T19:05:49.174Z"
}

###
GET http://localhost:3000/reminders/65b2a62069849894047f3669 HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWIyN2JhN2MxMWE0ZDI3YjMyMzk0N2YiLCJudW1iZXIiOiI5MTk3MTg0OTc2NzZAYy51cyIsImNoYXRJZCI6IjkxOTcxODQ5NzY3NkBjLnVzIiwiaXNWZXJpZmllZCI6ZmFsc2UsIl9fdiI6MCwiZW1haWwiOiJkaGFpcnlhc2hhaDk4QGdtYWlsLmNvbSIsImlhdCI6MTcwNjIwNjUzOX0.2YcJy91STE4UXU4NNtbN052W1ok8rBjDGhvjgLhPz-o

###
GET http://localhost:3000/reminders/ HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWIyN2JhN2MxMWE0ZDI3YjMyMzk0N2YiLCJudW1iZXIiOiI5MTk3MTg0OTc2NzZAYy51cyIsImNoYXRJZCI6IjkxOTcxODQ5NzY3NkBjLnVzIiwiaXNWZXJpZmllZCI6ZmFsc2UsIl9fdiI6MCwiZW1haWwiOiJkaGFpcnlhc2hhaDk4QGdtYWlsLmNvbSIsImlhdCI6MTcwNjIwNjUzOX0.2YcJy91STE4UXU4NNtbN052W1ok8rBjDGhvjgLhPz-o

###
DELETE http://localhost:3000/reminders/65b2a62069849894047f3669 HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWIyN2JhN2MxMWE0ZDI3YjMyMzk0N2YiLCJudW1iZXIiOiI5MTk3MTg0OTc2NzZAYy51cyIsImNoYXRJZCI6IjkxOTcxODQ5NzY3NkBjLnVzIiwiaXNWZXJpZmllZCI6ZmFsc2UsIl9fdiI6MCwiZW1haWwiOiJkaGFpcnlhc2hhaDk4QGdtYWlsLmNvbSIsImlhdCI6MTcwNjIwNjUzOX0.2YcJy91STE4UXU4NNtbN052W1ok8rBjDGhvjgLhPz-o